---
sudo: required
language: python
services: docker

env:
  matrix:
  - DISTRO="alpine-latest" ANSIBLE="devel"
  - DISTRO="alpine-edge"
  - DISTRO="archlinux" ANSIBLE="devel"
  - DISTRO="centos-6" ANSIBLE="devel"
  - DISTRO="centos-latest" ANSIBLE="devel"
  - DISTRO="debian-stable" ANSIBLE="devel"
  - DISTRO="debian-latest" ANSIBLE="devel"
  - DISTRO="debian-unstable"
  - DISTRO="fedora-latest" ANSIBLE="devel"
  - DISTRO="fedora-rawhide"
  - DISTRO="opensuse-leap" ANSIBLE="devel"
  - DISTRO="opensuse-tumbleweed" ANSIBLE="devel"
  - DISTRO="ubuntu-artful" ANSIBLE="devel"
  - DISTRO="ubuntu-latest" ANSIBLE="devel"
  - DISTRO="ubuntu-devel"

matrix:
  include:
  - env: ANSIBLE=">=2.5,<2.6"
  - env: ANSIBLE=">=2.6,<2.7"
  - env: ANSIBLE="latest"
  - env: ANSIBLE="devel"
  allow_failures:
  - env: DISTRO="alpine-latest" ANSIBLE="devel"
  - env: DISTRO="alpine-edge"
  - env: DISTRO="archlinux" ANSIBLE="devel"
  - env: DISTRO="centos-6" ANSIBLE="devel"
  - env: DISTRO="centos-latest" ANSIBLE="devel"
  - env: DISTRO="debian-stable" ANSIBLE="devel"
  - env: DISTRO="debian-latest" ANSIBLE="devel"
  - env: DISTRO="debian-unstable"
  - env: DISTRO="fedora-latest" ANSIBLE="devel"
  - env: DISTRO="fedora-rawhide"
  - env: DISTRO="opensuse-leap" ANSIBLE="devel"
  - env: DISTRO="opensuse-tumbleweed" ANSIBLE="devel"
  - env: DISTRO="ubuntu-artful" ANSIBLE="devel"
  - env: DISTRO="ubuntu-latest" ANSIBLE="devel"
  - env: DISTRO="ubuntu-devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${ANSIBLE}" != "latest" ] && [ "${ANSIBLE}" != "devel" ] ; then pip install ansible"${ANSIBLE}" ; fi
  - if [ "${ANSIBLE}" = "latest" ] ; then pip install ansible ; fi
  - if [ "${ANSIBLE}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${DISTRO}" ; else molecule test --scenario-name "${DISTRO}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
