---
sudo: required
language: python
services: docker

env:
  global:
  - ANSIBLE_MAJOR_N2=">=2.5,<2.6"
  - ANSIBLE_MAJOR_N1=">=2.6,<2.7"
  matrix:
  - DISTRO="alpine-latest" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="alpine-latest" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="alpine-latest" ANSIBLE="latest"
  - DISTRO="alpine-latest" ANSIBLE="devel"
  - DISTRO="alpine-edge" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="alpine-edge" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="alpine-edge" ANSIBLE="latest"
  - DISTRO="alpine-edge" ANSIBLE="devel"
  - DISTRO="archlinux" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="archlinux" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="archlinux" ANSIBLE="latest"
  - DISTRO="archlinux" ANSIBLE="devel"
  - DISTRO="centos-6" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="centos-6" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="centos-6" ANSIBLE="latest"
  - DISTRO="centos-6" ANSIBLE="devel"
  - DISTRO="centos-latest" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="centos-latest" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="centos-latest" ANSIBLE="latest"
  - DISTRO="centos-latest" ANSIBLE="devel"
  - DISTRO="debian-stable" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="debian-stable" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="debian-stable" ANSIBLE="latest"
  - DISTRO="debian-stable" ANSIBLE="devel"
  - DISTRO="debian-latest" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="debian-latest" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="debian-latest" ANSIBLE="latest"
  - DISTRO="debian-latest" ANSIBLE="devel"
  - DISTRO="debian-unstable" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="debian-unstable" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="debian-unstable" ANSIBLE="latest"
  - DISTRO="debian-unstable" ANSIBLE="devel"
  - DISTRO="fedora-latest" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="fedora-latest" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="fedora-latest" ANSIBLE="latest"
  - DISTRO="fedora-latest" ANSIBLE="devel"
  - DISTRO="fedora-rawhide" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="fedora-rawhide" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="fedora-rawhide" ANSIBLE="latest"
  - DISTRO="fedora-rawhide" ANSIBLE="devel"
  - DISTRO="opensuse-leap" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="opensuse-leap" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="opensuse-leap" ANSIBLE="latest"
  - DISTRO="opensuse-leap" ANSIBLE="devel"
  - DISTRO="opensuse-tumbleweed" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="opensuse-tumbleweed" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="opensuse-tumbleweed" ANSIBLE="latest"
  - DISTRO="opensuse-tumbleweed" ANSIBLE="devel"
  - DISTRO="ubuntu-artful" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="ubuntu-artful" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="ubuntu-artful" ANSIBLE="latest"
  - DISTRO="ubuntu-artful" ANSIBLE="devel"
  - DISTRO="ubuntu-latest" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="ubuntu-latest" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="ubuntu-latest" ANSIBLE="latest"
  - DISTRO="ubuntu-latest" ANSIBLE="devel"
  - DISTRO="ubuntu-devel" ANSIBLE="${ANSIBLE_MAJOR_N2}"
  - DISTRO="ubuntu-devel" ANSIBLE="${ANSIBLE_MAJOR_N1}"
  - DISTRO="ubuntu-devel" ANSIBLE="latest"
  - DISTRO="ubuntu-devel" ANSIBLE="devel"

matrix:
  allow_failures:
  - env: DISTRO="alpine-latest" ANSIBLE="devel"
  - env: DISTRO="alpine-edge"
  - env: DISTRO="archlinux" ANSIBLE="devel"
  - env: DISTRO="centos-6" ANSIBLE="devel"
  - env: DISTRO="centos-latest" ANSIBLE="devel"
  - env: DISTRO="debian-stable" ANSIBLE="devel"
  - env: DISTRO="debian-latest" ANSIBLE="devel"
  - env: DISTRO="debian-unstable"
  - env: DISTRO="fedora-latest" ANSIBLE="devel"
  - env: DISTRO="fedora-rawhide"
  - env: DISTRO="opensuse-leap" ANSIBLE="devel"
  - env: DISTRO="opensuse-tumbleweed" ANSIBLE="devel"
  - env: DISTRO="ubuntu-artful" ANSIBLE="devel"
  - env: DISTRO="ubuntu-latest" ANSIBLE="devel"
  - env: DISTRO="ubuntu-devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${ANSIBLE}" != "latest" ] && [ "${ANSIBLE}" != "devel" ] ; then pip install ansible"${ANSIBLE}" ; fi
  - if [ "${ANSIBLE}" = "latest" ] ; then pip install ansible ; fi
  - if [ "${ANSIBLE}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${DISTRO}" ; else molecule test --scenario-name "${DISTRO}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
