---
# tasks file for users

- name: Bootstrap users
  block:

    - name: Ensure required system packages are present
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ users_packages.split() }}"
      register: users_packages_install
      until: users_packages_install is succeeded
      retries: 3
      delay: 60

    - name: Create user groups
      group:
        name: "{{ item.name }}"
        state: present
        gid: "{{ item.gid | default(omit) }}"
      with_items: "{{ users_groups }}"
      when: item.state | default('present') == 'present'
      tags: ['users', 'groups', 'configuration']

    - name: Create group per user
      group:
        name: "{{ item.name }}"
        state: present
        gid: "{{ item.gid | default(item.uid) | default(omit) }}"
      with_items: "{{ users }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - item.state | default('present') == 'present'
        - "'group' not in item"
        - users_group_per_user | bool
      tags: ['users', 'configuration']

    - name: Setup users
      user:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
        uid: "{{ item.uid | default(omit) }}"
        comment: "{{ item.comment if item.comment is defined else '' }}"
        group: "{{ item.group | default(item.name if users_group_per_user | bool else users_group) }}"
        # empty string removes user from all secondary groups
        groups: "{{ item.groups | join(', ') if 'groups' in item else '' }}"
        append: "{{ item.append | default(omit) }}"
        password: "{{ item.password if item.password is defined else '!' }}"
        update_password: "{{ item.update_password | default(omit) }}"
        create_home: "{{ item.create_home | default('yes' if users_create_home | bool else 'no') }}"
        home: "{{ item.home | default('/home/' + item.name) }}"
        shell: "{{ item.shell if item.shell is defined else users_shell }}"
        remove: "{{ item.remove | default(omit) }}"
        force: "{{ item.force | default(omit) }}"
      with_items: "{{ users }}"
      loop_control:
        label: "{{ item.name }}"
      tags: ['users', 'configuration']

    - name: Delete group per user
      group:
        name: "{{ item.name }}"
        state: absent
        gid: "{{ item.gid | default(item.uid) | default(omit) }}"
      with_items: "{{ users }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - item.state | default('present') == 'absent'
        - "'group' not in item"
        - users_group_per_user | bool
      tags: ['users', 'configuration']

    - name: Delete user groups
      group:
        name: "{{ item.name }}"
        state: absent
        gid: "{{ item.gid | default(omit) }}"
      with_items: "{{ users_groups }}"
      when: item.state | default('present') == 'absent'
      tags: ['users', 'groups', 'configuration']

    - name: Prepare users cron permission
      template:
        src: cron.allow.j2
        dest: /etc/cron.allow
        force: no
      tags: ['users', 'configuration']

    - name: Setup users cron permission
      lineinfile:
        state: "{{ 'present' if item.cron | default('no') | bool
                and item.state | default('present') == 'present' else 'absent' }}"
        path: /etc/cron.allow
        line: "{{ item.name }}"
      with_items: "{{ users }}"
      loop_control:
        label: "{{ item.name }}"
      tags: ['users', 'configuration']

    - name: Add user sudo options
      template:
        src: sudo.j2
        dest: "/etc/sudoers.d/{{ item.name }}"
      when:
        - item.state | default('present') == 'present'
        - item.sudo | default('no') | bool
      with_items:
        - "{{ users }}"
      loop_control:
        label: "{{ item.name }}"
      tags: ['users', 'configuration']

    - name: Remove user sudo options
      file:
        state: absent
        path: "/etc/sudoers.d/{{ item.name }}"
      when:
        - (not item.sudo | default('no') | bool or item.state | default('present') == 'absent')
      with_items: "{{ users }}"
      loop_control:
        label: "{{ item.name }}"
      tags: ['users', 'configuration']

    - name: Setup user SSH keys
      include_tasks: keys.yml
      with_items: "{{ users }}"
      loop_control:
        loop_var: users_user
        label: "{{ users_user.name }}"
      when:
        - users_user.state | default('present') == 'present'
        - users_user.create_home | default(users_create_home) | bool
      tags: ['users', 'configuration']

    - name: Setup user profile
      blockinfile:
        block: "{{ item.profile }}"
        dest: "{{ item.home | default('/home/' + item.name) }}/.profile"
        owner: "{{ item.name }}"
        group: "{{ item.group | default(item.name if users_group_per_user | bool else users_group) }}"
        mode: 0644
        create: yes
      when:
        - item.state | default('present') == 'present'
        - item.create_home | default(users_create_home) | bool
        - item.profile is defined
      with_items: "{{ users }}"
      loop_control:
        label: "{{ item.name }}"
      tags: ['users', 'configuration']

  vars:
    ansible_user: "{{ bootstrap_ansible_user | default(omit) }}"
