---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - role: rembik.bootstrap
    - role: ansible-role-users
      vars:
        users_ssh_key_dir: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
        users_groups:
          - name: users
          - name: bin
        users:
          - name: nouser
            comment: No User
            create_home: no
          - name: molecule
            comment: Ansible Management User
            uid: 2001
            groups: [users, bin]
            cron: yes
            sudo: yes
            profile: |
              alias ll='ls -lah'
              alias cp='cp -iv'
            ssh_key:
              - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABWBILQeRSYYmGea/WIf6kd nobody@example.com"
            generate_ssh_key: yes
          - name: test
            comment: Ansible Test User
            uid: 2002
            groups: [users]
            home: /test
            cron: yes
            generate_ssh_key: yes
          - name: user
            comment: User
            uid: 2003
            groups: [users]
            shell: /bin/sh
