---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  options:
    config-file: molecule/.yamllint
platforms:
  # https://app.vagrantup.com/boxes/search
  - name: "${MOLECULE_INSTANCE_PREFIX:-instance}-${MOLECULE_DISTRO:-centos-latest}-vagrant"
    image: ${MOLECULE_VBOX:-centos/7}
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_plugins: /usr/lib/python2.7/site-packages/ara/plugins/callbacks
  playbook:
    converge: ${MOLECULE_PLAYBOOK:-../playbook.yml}
scenario:
  name: vagrant
verifier:
  name: goss
  directory: ../tests
  lint:
    name: yamllint
