---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: molecule/.yamllint.yml
platforms:
  # https://docs.aws.amazon.com/en_us/AWSEC2/latest/UserGuide/finding-an-ami.html
  - name: instance-amazon-linux-2
    image: ami-02ea8f348fa28c108
    instance_type: t2.micro
    vpc_subnet_id: ${MOLECULE_VPC_SUBNET_ID}
  - name: instance-centos-latest
    image: ami-9a183671
    instance_type: t2.micro
    vpc_subnet_id: ${MOLECULE_VPC_SUBNET_ID}
  - name: instance-fedora-latest
    image: ami-0f904cfaa69a1c64c
    instance_type: t2.micro
    vpc_subnet_id: ${MOLECULE_VPC_SUBNET_ID}
  - name: instance-ubuntu-latest
    image: ami-0bdf93799014acdc4
    instance_type: t2.micro
    vpc_subnet_id: ${MOLECULE_VPC_SUBNET_ID}
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_plugins: /usr/lib/python2.7/site-packages/ara/plugins/callbacks
  playbook:
    converge: ${MOLECULE_PLAYBOOK:-../playbook.yml}
  inventory:
    host_vars:
      instance-ubuntu-latest:
        ansible_user: ubuntu
      instance-centos-latest:
        ansible_user: centos
      instance-fedora-latest:
        ansible_user: fedora
scenario:
  name: ec2-all
verifier:
  name: goss
  directory: ../tests/
  lint:
    name: yamllint
