---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: molecule/.yamllint
platforms:
  # https://docs.aws.amazon.com/en_us/AWSEC2/latest/UserGuide/finding-an-ami.html
  - name: instance_amazonlinux_latest_ec2
    image: ami-084ab95c0cbe247e5
    instance_type: t2.micro
    vpc_subnet_id: ${TEST_EC2_VPC_SUBNET_ID:-""}
    root_device:
      device_name: /dev/xvda
    groups:
      - amazonlinux_latest_ec2
  - name: instance_centos_latest_ec2
    image: ami-dd3c0f36
    instance_type: t2.micro
    vpc_subnet_id: ${TEST_EC2_VPC_SUBNET_ID:-""}
    groups:
      - centos_latest_ec2
  - name: instance_debian_latest_ec2
    image: ami-0ca467408e84df23c
    instance_type: t2.micro
    vpc_subnet_id: ${TEST_EC2_VPC_SUBNET_ID:-""}
    root_device:
      device_name: xvda
    groups:
      - debian_latest_ec2
  - name: instance_fedora_latest_ec2
    image: ami-0417b5ec8768794f9
    instance_type: t2.micro
    vpc_subnet_id: ${TEST_EC2_VPC_SUBNET_ID:-""}
    groups:
      - fedora_latest_ec2
  - name: instance_redhat_latest_ec2
    image: ami-875042eb
    instance_type: t2.micro
    vpc_subnet_id: ${TEST_EC2_VPC_SUBNET_ID:-""}
    groups:
      - redhat_latest_ec2
  - name: instance_ubuntu_latest_ec2
    image: ami-0cf8fa6a01bb07363
    instance_type: t2.micro
    vpc_subnet_id: ${TEST_EC2_VPC_SUBNET_ID:-""}
    groups:
      - ubuntu_latest_ec2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_plugins: /usr/lib/python${TOX_PYTHON_VERSION:-3.7}/site-packages/ara/plugins/callbacks
  playbooks:
    converge: ${TEST_PLAYBOOK:-../playbook.yml}
  inventory:
    group_vars:
      amazonlinux_latest_ec2:
        bootstrap_user: ec2-user
      centos_latest_ec2:
        bootstrap_user: centos
      debian_latest_ec2:
        bootstrap_user: admin
      fedora_latest_ec2:
        bootstrap_user: fedora
      redhat_latest_ec2:
        bootstrap_user: ec2-user
      ubuntu_latest_ec2:
        bootstrap_user: ubuntu
scenario:
  name: ec2-all
verifier:
  name: goss
  directory: ../tests
  lint:
    name: yamllint
