---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/.yamllint
platforms:
  # https://hub.docker.com/search/?type=image
  - name: "${MOLECULE_INSTANCE_PREFIX:-instance}-${MOLECULE_DISTRO:-centos-latest}-${MOLECULE_TOXENV:-docker}"
    image: ${MOLECULE_DOCKER:-centos:latest}
    command: ${MOLECULE_COMMAND:-sleep infinity}
    groups:
      - ${MOLECULE_DISTRO:-centos-latest}-docker
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_plugins: /usr/lib/python2.7/site-packages/ara/plugins/callbacks
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-../playbook.yml}
  inventory:
    group_vars:
      fedora-rawhide-docker:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
verifier:
  name: goss
  directory: ../tests
  lint:
    name: yamllint
