---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/.yamllint
platforms:
  # https://hub.docker.com/search/?type=image
  - name: "${TEST_INSTANCE_PREFIX:-instance}_${TEST_DISTRO:-centos_latest}_${TOX_ENVNAME:-docker}"
    image: ${TEST_DOCKER_IMAGE:-centos:latest}
    pre_build_image: yes
    command: ${TEST_DOCKER_COMMAND:-sleep infinity}
    groups:
      - ${TEST_DISTRO:-centos_latest}_docker
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_plugins: /usr/lib/python${TOX_PYTHON_VERSION:-3.7}/site-packages/ara/plugins/callbacks
  playbooks:
    converge: ${TEST_PLAYBOOK:-../playbook.yml}
  inventory:
    group_vars:
      alpine_latest_docker:
        ansible_python_interpreter: /usr/bin/python3
      alpine_edge_docker:
        ansible_python_interpreter: /usr/bin/python3
      centos_latest_docker:
        ansible_python_interpreter: /usr/bin/python3
      debian_latest_docker:
        ansible_python_interpreter: /usr/bin/python3
      debian_unstable_docker:
        ansible_python_interpreter: /usr/bin/python3
      fedora_latest_docker:
        ansible_python_interpreter: /usr/bin/python3
      fedora_rawhide_docker:
        ansible_python_interpreter: /usr/bin/python3
      redhat_latest_docker:
        ansible_python_interpreter: /usr/bin/python3
      ubuntu_latest_docker:
        ansible_python_interpreter: /usr/bin/python3
      ubuntu_devel_docker:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
verifier:
  name: goss
  directory: ../tests
  lint:
    name: yamllint
